#!/usr/bin/env bash

# ================== #
# common unix commands
alias ..="cd .."
alias ...="cd ../.."
alias ....="cd ../../.."
alias recd="cd .. && cd -"
alias cdw="cd $MY_WORK_DIR"
alias cdv="cd $MY_WWW_DIR"
alias cdd="cd $HOME/Downloads"
alias cdde="cd $HOME/Desktop"

# Enable aliases to be sudo’ed
alias sudo='sudo '

alias ll="ls -laGh"

# Intuitive map function
# For example, to list all directories that contain a certain file:
# find . -name .gitattributes | map dirname
alias map="xargs -n1"

# shell reload
alias reload="exec $SHELL -l"

# get local ip
alias localip="ipconfig getifaddr en0"

# ================== #
# git
alias g="git"

# ================== #
# bundler
alias bex="bundler exec"

# ================== #
# vagrant
alias vu="vagrant up"
alias vus="vagrant up && vagrant ssh"
alias vs="vagrant ssh"
alias vh="vagrant halt"

# ================== #
# docker
alias dox="docker exec"
alias dops="docker ps"
alias dopsa="docker ps -a"
alias dor="docker run"
alias dok="docker kill"
alias dob="docker build"
alias doka="docker rm -f $(docker ps -q -a)"
alias docu="docker-compose up"
alias docd="docker-compose down"

# ================== #
# OSX specific #

# Recursively delete `.DS_Store` files
alias cleanup="find . -type f -name '*.DS_Store' -ls -delete"

# Disable Spotlight
alias spotoff="sudo launchctl unload -w /System/Library/LaunchDaemons/com.apple.metadata.mds.plist"
# Enable Spotlight
alias spoton="sudo launchctl load -w /System/Library/LaunchDaemons/com.apple.metadata.mds.plist"

# Lock the screen (when going AFK)
alias afk="/System/Library/CoreServices/Menu\ Extras/User.menu/Contents/Resources/CGSession -suspend"
