#!/usr/bin/env bash

# shorthand for history | grep
# arguments: search-pattern
function meme() {
  history | grep $1
}

# Create a new directory and enter it
function mkd() {
	mkdir -p "$@" && cd "$_";
}

# Determine size of a file or total size of a directory
function fs() {
	if du -b /dev/null > /dev/null 2>&1; then
		local arg=-sbh;
	else
		local arg=-sh;
	fi
	if [[ -n "$@" ]]; then
		du $arg -- "$@";
	else
		du $arg .[^.]* ./*;
	fi;
}

# Start an HTTP server from a directory, optionally specifying the port
function server() {
	local port="${1:-8000}";
	sleep 1 && open "http://localhost:${port}/" &
	# Set the default Content-Type to `text/plain` instead of `application/octet-stream`
	# And serve everything as UTF-8 (although not technically correct, this doesn’t break anything for binary files)
	python -c $'import SimpleHTTPServer;\nmap = SimpleHTTPServer.SimpleHTTPRequestHandler.extensions_map;\nmap[""] = \
	"text/plain";\nfor key, value in map.items():\n\tmap[key] = value + ";charset=UTF-8";\nSimpleHTTPServer.test();' "$port";
}

# Configure vim.
function configure_vim() {
  git clone https://github.com/VundleVim/Vundle.vim.git ~/.vim/bundle/Vundle.vim
  vim +PluginInstall +qall
}

function clojide() {
  open "http://localhost:4000"
  lein nightlight
}

# List all formulas that aren't dependent of any other formulas (leaves) and in front of them list all its dependencies
function brew-inventory() {
	brew leaves | xargs brew deps --installed --for-each | sed "s/^.*:/$(tput setaf 4)&$(tput sgr0)/"
}

# Watch for something to happen and execute a command on this event
# Example: watch-cmd "/path/to/file.css" "make css"
function watch-cmd() {
	WATCH_COMMAND=${1}
	COMMAND=${2}
	while true; do
	  watch -d -g "${WATCH_COMMAND}"
	  ${COMMAND}
	  sleep 1     # to allow break script by Ctrl+c
	done
}

# SSH into MacOS Docker desktop virtual machine
function docker-vm-ssh() {
	stty -echo -icanon && nc -U ~/Library/Containers/com.docker.docker/Data/debug-shell.sock && stty sane
}
