#!/usr/bin/env bash

# golang
export GOROOT=/usr/local/opt/go/libexec
export GOPATH="${MY_WORK_DIR}/go"
export PATH=$PATH:$GOROOT/bin:$GOPATH/bin

# If your Rust is installed via rustup.
if [ -f $HOME/.cargo/env ]; then
  source $HOME/.cargo/env
fi

export PATH="/usr/local/sbin:$PATH"

if [ -f $HOME/.rbenv/shims ]; then
  PATH="$HOME/.rbenv/shims:$PATH"
fi

# Add vscode executable for macOS
PATH="$PATH:/Applications/Visual Studio Code.app/Contents/Resources/app/bin"

# Add /usr/local/bin
PATH="/usr/local/bin:$PATH"
