#!/usr/bin/env bash

# golang
export GOROOT=/usr/local/opt/go/libexec
export GOPATH="${MY_WORK_DIR}/go"
export PATH=$PATH:$GOROOT/bin:$GOPATH/bin

# If your Rust is installed via rustup.
if [ -f $HOME/.cargo/env ]; then
  source $HOME/.cargo/env
fi

export PATH="/usr/local/sbin:$PATH"

export PATH="~/.rbenv/shims:$PATH"
